# application config
server:
  port: ${SERVER_PORT:8122}

# spring config
spring:
  application:
    name: ${APPLICATION_NAME:693c018b7390943f7d9b667715c5232a6df15572c088854028782ed84cd2a826}

  # mongo db config
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/ActivityQueryService}
      database: ${MONGODB_DATABASE:ActivityQueryService}

  # rabbitmq config
  rabbitmq:
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    ignoreDeclarationException: ${RABBITMQ_IGNORE_DECLARATION_EXCEPTION:true}
    concurrentConsumers: ${RABBITMQ_CONCURRENT_CONSUMERS:3}
    maxConcurrentConsumers: ${RABBITMQ_MAX_CONCURRENT_CONSUMERS:10}
    receiveTimeout: ${RABBITMQ_RECEIVE_TIMEOUT:100000}

# log
logging:
  level:
    root: debug
    org.springframework.data.mongodb.core.MongoTemplate: debug